<?php
require __DIR__ . '/../config.php';
$user=api_user(); $pdo=db(); $action=$_REQUEST['action'] ?? 'list';
if($_SERVER['REQUEST_METHOD']==='POST' && !verify_csrf($_POST['csrf'] ?? null)) json_response(['ok'=>false,'error'=>'Bad CSRF token.'],403);
function direct_conversation(PDO $pdo,int $a,int $b): int { if(users_blocked($pdo,$a,$b)) json_response(['ok'=>false,'error'=>'DMs are blocked between these users.'],403); $q=$pdo->prepare("SELECT c.id FROM conversations c JOIN conversation_members x ON x.conversation_id=c.id AND x.user_id=? JOIN conversation_members y ON y.conversation_id=c.id AND y.user_id=? WHERE c.type='dm' LIMIT 1"); $q->execute([$a,$b]); if($id=$q->fetchColumn()) return (int)$id; $pdo->beginTransaction(); $pdo->exec("INSERT INTO conversations (is_direct,type) VALUES (1,'dm')"); $id=(int)$pdo->lastInsertId(); $pdo->prepare('INSERT INTO conversation_members (conversation_id,user_id) VALUES (?,?),(?,?)')->execute([$id,$a,$id,$b]); $pdo->commit(); return $id; }
function relation(PDO $pdo,int $me,int $other): string { $f=$pdo->prepare('SELECT 1 FROM friends WHERE user_id=? AND friend_id=?'); $f->execute([$me,$other]); if($f->fetchColumn()) return 'friends'; $in=$pdo->prepare("SELECT id FROM friend_requests WHERE sender_id=? AND receiver_id=? AND status='pending'"); $in->execute([$other,$me]); if($in->fetchColumn()) return 'incoming'; $out=$pdo->prepare("SELECT id FROM friend_requests WHERE sender_id=? AND receiver_id=? AND status='pending'"); $out->execute([$me,$other]); if($out->fetchColumn()) return 'sent'; return 'none'; }
if($action==='search'){ $q=trim($_GET['q']??''); $s=$pdo->prepare('SELECT id,username,avatar,status,last_seen FROM users WHERE username LIKE ? AND id<>? ORDER BY username LIMIT 10'); $s->execute([$q.'%',$user['id']]); $rows=$s->fetchAll(); foreach($rows as &$r){$r['relation']=relation($pdo,(int)$user['id'],(int)$r['id']);} json_response(['ok'=>true,'users'=>$rows]); }
if($action==='request'){ $rid=(int)($_POST['user_id']??0); if($rid===(int)$user['id']) json_response(['ok'=>false,'error'=>'Cannot add yourself.'],422); if(users_blocked($pdo,(int)$user['id'],$rid)) json_response(['ok'=>false,'error'=>'Blocked users cannot be friended.'],403); $rel=relation($pdo,(int)$user['id'],$rid); if($rel==='friends'||$rel==='sent') json_response(['ok'=>true,'state'=>$rel]); if($rel==='incoming'){ $req=$pdo->prepare("SELECT * FROM friend_requests WHERE sender_id=? AND receiver_id=? AND status='pending'"); $req->execute([$rid,$user['id']]); $row=$req->fetch(); if($row){ $pdo->prepare("UPDATE friend_requests SET status='accepted', seen_at=NOW() WHERE id=?")->execute([$row['id']]); $pdo->prepare('INSERT IGNORE INTO friends (user_id,friend_id) VALUES (?,?),(?,?)')->execute([$rid,$user['id'],$user['id'],$rid]); } json_response(['ok'=>true,'state'=>'friends']); } else { $pdo->prepare("INSERT IGNORE INTO friend_requests (sender_id,receiver_id,status) VALUES (?,?,'pending')")->execute([$user['id'],$rid]); json_response(['ok'=>true,'state'=>'sent']); } }
if($action==='respond'){ $id=(int)($_POST['request_id']??0); $decision=($_POST['decision']??'decline')==='accept'?'accepted':'declined'; $r=$pdo->prepare("SELECT * FROM friend_requests WHERE id=? AND receiver_id=? AND status='pending'"); $r->execute([$id,$user['id']]); $req=$r->fetch(); if(!$req) json_response(['ok'=>false,'error'=>'Request not found.'],404); $pdo->prepare('UPDATE friend_requests SET status=?, seen_at=NOW() WHERE id=?')->execute([$decision,$id]); if($decision==='accepted') $pdo->prepare('INSERT IGNORE INTO friends (user_id,friend_id) VALUES (?,?),(?,?)')->execute([$req['sender_id'],$req['receiver_id'],$req['receiver_id'],$req['sender_id']]); json_response(['ok'=>true]); }
if($action==='unfriend'){ $fid=(int)($_POST['user_id']??0); $pdo->prepare('DELETE FROM friends WHERE (user_id=? AND friend_id=?) OR (user_id=? AND friend_id=?)')->execute([$user['id'],$fid,$fid,$user['id']]); json_response(['ok'=>true]); }
if($action==='block'){ $bid=(int)($_POST['user_id']??0); $pdo->prepare('INSERT IGNORE INTO blocked_users (blocker_id,blocked_id) VALUES (?,?)')->execute([$user['id'],$bid]); $pdo->prepare('DELETE FROM friends WHERE (user_id=? AND friend_id=?) OR (user_id=? AND friend_id=?)')->execute([$user['id'],$bid,$bid,$user['id']]); json_response(['ok'=>true]); }
if($action==='start'){ $fid=(int)($_POST['friend_id']??$_POST['user_id']??0); $cid=direct_conversation($pdo,(int)$user['id'],$fid); $pdo->prepare('DELETE FROM hidden_conversations WHERE user_id=? AND conversation_id=?')->execute([$user['id'],$cid]); json_response(['ok'=>true,'conversation_id'=>$cid]); }
$s=$pdo->prepare('SELECT u.id,u.username,u.avatar,u.status,u.last_seen FROM friends f JOIN users u ON u.id=f.friend_id WHERE f.user_id=? ORDER BY u.username'); $s->execute([$user['id']]);
$r=$pdo->prepare('SELECT fr.id,u.id user_id,u.username,u.avatar,u.status FROM friend_requests fr JOIN users u ON u.id=fr.sender_id WHERE fr.receiver_id=? AND fr.status="pending" ORDER BY fr.created_at DESC'); $r->execute([$user['id']]);
json_response(['ok'=>true,'friends'=>$s->fetchAll(),'requests'=>$r->fetchAll()]);
